leveldb:
  bloom_bits: 10
  enable_direct_io: false
  enable_compaction: true
  use_global_index: false
  thread_compaction: 8
  block_cache_size: "10GB" # e.g. "100MB" or "10GB"
  memtable_size: "128MB" # e.g. "64MB"
  sst_file_size: "32MB"
rocksdb:
  bloom_bits: 10
  enable_direct_io: false
  enable_compaction: true
  use_global_index: false
  thread_compaction: 8
  block_cache_size: "8GB" # e.g. "100MB" or "10GB"
  memtable_size: "128MB" # e.g. "64MB"
  sst_file_size: "32MB"
