leveldb:
  bloom_bits: 10
  enable_direct_io: true
  enable_compaction: true
  use_global_index: false
  use_queue_monitor: false
  thread_compaction: 4
  block_cache_size: "1GB" # e.g. "100MB" or "10GB"
  memtable_size: "64MB" # e.g. "64MB"
  sst_file_size: "32MB"
rocksdb:
  bloom_bits: 10
  enable_direct_io: true
  enable_compaction: true
  use_global_index: false
  use_queue_monitor: false
  thread_compaction: 4
  block_cache_size: "1GB" # e.g. "100MB" or "10GB"
  memtable_size: "64MB" # e.g. "64MB"
  sst_file_size: "64MB"
