# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kvgroup/zqy/YCSB-C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kvgroup/zqy/YCSB-C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kvgroup/zqy/YCSB-C/CMakeFiles /home/kvgroup/zqy/YCSB-C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kvgroup/zqy/YCSB-C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ycsbc

# Build rule for target.
ycsbc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ycsbc
.PHONY : ycsbc

# fast build rule for target.
ycsbc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/build
.PHONY : ycsbc/fast

#=============================================================================
# Target rules for targets named config_reader_test

# Build rule for target.
config_reader_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config_reader_test
.PHONY : config_reader_test

# fast build rule for target.
config_reader_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/build
.PHONY : config_reader_test/fast

#=============================================================================
# Target rules for targets named histogram_test

# Build rule for target.
histogram_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 histogram_test
.PHONY : histogram_test

# fast build rule for target.
histogram_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/build
.PHONY : histogram_test/fast

#=============================================================================
# Target rules for targets named leveldb_test

# Build rule for target.
leveldb_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldb_test
.PHONY : leveldb_test

# fast build rule for target.
leveldb_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/build
.PHONY : leveldb_test/fast

core/core_workload.o: core/core_workload.cc.o
.PHONY : core/core_workload.o

# target to build an object file
core/core_workload.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/core/core_workload.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/core/core_workload.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/core/core_workload.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/core/core_workload.cc.o
.PHONY : core/core_workload.cc.o

core/core_workload.i: core/core_workload.cc.i
.PHONY : core/core_workload.i

# target to preprocess a source file
core/core_workload.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/core/core_workload.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/core/core_workload.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/core/core_workload.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/core/core_workload.cc.i
.PHONY : core/core_workload.cc.i

core/core_workload.s: core/core_workload.cc.s
.PHONY : core/core_workload.s

# target to generate assembly for a file
core/core_workload.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/core/core_workload.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/core/core_workload.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/core/core_workload.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/core/core_workload.cc.s
.PHONY : core/core_workload.cc.s

core/histogram.o: core/histogram.cc.o
.PHONY : core/histogram.o

# target to build an object file
core/histogram.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/core/histogram.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/core/histogram.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/core/histogram.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/core/histogram.cc.o
.PHONY : core/histogram.cc.o

core/histogram.i: core/histogram.cc.i
.PHONY : core/histogram.i

# target to preprocess a source file
core/histogram.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/core/histogram.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/core/histogram.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/core/histogram.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/core/histogram.cc.i
.PHONY : core/histogram.cc.i

core/histogram.s: core/histogram.cc.s
.PHONY : core/histogram.s

# target to generate assembly for a file
core/histogram.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/core/histogram.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/core/histogram.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/core/histogram.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/core/histogram.cc.s
.PHONY : core/histogram.cc.s

db/db_factory.o: db/db_factory.cc.o
.PHONY : db/db_factory.o

# target to build an object file
db/db_factory.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/db_factory.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/db_factory.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/db_factory.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/db_factory.cc.o
.PHONY : db/db_factory.cc.o

db/db_factory.i: db/db_factory.cc.i
.PHONY : db/db_factory.i

# target to preprocess a source file
db/db_factory.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/db_factory.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/db_factory.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/db_factory.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/db_factory.cc.i
.PHONY : db/db_factory.cc.i

db/db_factory.s: db/db_factory.cc.s
.PHONY : db/db_factory.s

# target to generate assembly for a file
db/db_factory.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/db_factory.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/db_factory.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/db_factory.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/db_factory.cc.s
.PHONY : db/db_factory.cc.s

db/hashtable_db.o: db/hashtable_db.cc.o
.PHONY : db/hashtable_db.o

# target to build an object file
db/hashtable_db.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/hashtable_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/hashtable_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/hashtable_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/hashtable_db.cc.o
.PHONY : db/hashtable_db.cc.o

db/hashtable_db.i: db/hashtable_db.cc.i
.PHONY : db/hashtable_db.i

# target to preprocess a source file
db/hashtable_db.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/hashtable_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/hashtable_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/hashtable_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/hashtable_db.cc.i
.PHONY : db/hashtable_db.cc.i

db/hashtable_db.s: db/hashtable_db.cc.s
.PHONY : db/hashtable_db.s

# target to generate assembly for a file
db/hashtable_db.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/hashtable_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/hashtable_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/hashtable_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/hashtable_db.cc.s
.PHONY : db/hashtable_db.cc.s

db/leveldb_db.o: db/leveldb_db.cc.o
.PHONY : db/leveldb_db.o

# target to build an object file
db/leveldb_db.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/leveldb_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/leveldb_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/leveldb_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/leveldb_db.cc.o
.PHONY : db/leveldb_db.cc.o

db/leveldb_db.i: db/leveldb_db.cc.i
.PHONY : db/leveldb_db.i

# target to preprocess a source file
db/leveldb_db.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/leveldb_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/leveldb_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/leveldb_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/leveldb_db.cc.i
.PHONY : db/leveldb_db.cc.i

db/leveldb_db.s: db/leveldb_db.cc.s
.PHONY : db/leveldb_db.s

# target to generate assembly for a file
db/leveldb_db.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/leveldb_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/leveldb_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/leveldb_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/leveldb_db.cc.s
.PHONY : db/leveldb_db.cc.s

db/rocksdb_db.o: db/rocksdb_db.cc.o
.PHONY : db/rocksdb_db.o

# target to build an object file
db/rocksdb_db.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/rocksdb_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/rocksdb_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/rocksdb_db.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/rocksdb_db.cc.o
.PHONY : db/rocksdb_db.cc.o

db/rocksdb_db.i: db/rocksdb_db.cc.i
.PHONY : db/rocksdb_db.i

# target to preprocess a source file
db/rocksdb_db.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/rocksdb_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/rocksdb_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/rocksdb_db.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/rocksdb_db.cc.i
.PHONY : db/rocksdb_db.cc.i

db/rocksdb_db.s: db/rocksdb_db.cc.s
.PHONY : db/rocksdb_db.s

# target to generate assembly for a file
db/rocksdb_db.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/db/rocksdb_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/db/rocksdb_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/db/rocksdb_db.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/db/rocksdb_db.cc.s
.PHONY : db/rocksdb_db.cc.s

tests/config_reader_test.o: tests/config_reader_test.cc.o
.PHONY : tests/config_reader_test.o

# target to build an object file
tests/config_reader_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/tests/config_reader_test.cc.o
.PHONY : tests/config_reader_test.cc.o

tests/config_reader_test.i: tests/config_reader_test.cc.i
.PHONY : tests/config_reader_test.i

# target to preprocess a source file
tests/config_reader_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/tests/config_reader_test.cc.i
.PHONY : tests/config_reader_test.cc.i

tests/config_reader_test.s: tests/config_reader_test.cc.s
.PHONY : tests/config_reader_test.s

# target to generate assembly for a file
tests/config_reader_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_reader_test.dir/build.make CMakeFiles/config_reader_test.dir/tests/config_reader_test.cc.s
.PHONY : tests/config_reader_test.cc.s

tests/histogram_test.o: tests/histogram_test.cc.o
.PHONY : tests/histogram_test.o

# target to build an object file
tests/histogram_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/tests/histogram_test.cc.o
.PHONY : tests/histogram_test.cc.o

tests/histogram_test.i: tests/histogram_test.cc.i
.PHONY : tests/histogram_test.i

# target to preprocess a source file
tests/histogram_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/tests/histogram_test.cc.i
.PHONY : tests/histogram_test.cc.i

tests/histogram_test.s: tests/histogram_test.cc.s
.PHONY : tests/histogram_test.s

# target to generate assembly for a file
tests/histogram_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/histogram_test.dir/build.make CMakeFiles/histogram_test.dir/tests/histogram_test.cc.s
.PHONY : tests/histogram_test.cc.s

tests/leveldb_test.o: tests/leveldb_test.cc.o
.PHONY : tests/leveldb_test.o

# target to build an object file
tests/leveldb_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/tests/leveldb_test.cc.o
.PHONY : tests/leveldb_test.cc.o

tests/leveldb_test.i: tests/leveldb_test.cc.i
.PHONY : tests/leveldb_test.i

# target to preprocess a source file
tests/leveldb_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/tests/leveldb_test.cc.i
.PHONY : tests/leveldb_test.cc.i

tests/leveldb_test.s: tests/leveldb_test.cc.s
.PHONY : tests/leveldb_test.s

# target to generate assembly for a file
tests/leveldb_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leveldb_test.dir/build.make CMakeFiles/leveldb_test.dir/tests/leveldb_test.cc.s
.PHONY : tests/leveldb_test.cc.s

ycsbc.o: ycsbc.cc.o
.PHONY : ycsbc.o

# target to build an object file
ycsbc.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/ycsbc.cc.o
.PHONY : ycsbc.cc.o

ycsbc.i: ycsbc.cc.i
.PHONY : ycsbc.i

# target to preprocess a source file
ycsbc.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/ycsbc.cc.i
.PHONY : ycsbc.cc.i

ycsbc.s: ycsbc.cc.s
.PHONY : ycsbc.s

# target to generate assembly for a file
ycsbc.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ycsbc.dir/build.make CMakeFiles/ycsbc.dir/ycsbc.cc.s
.PHONY : ycsbc.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... config_reader_test"
	@echo "... histogram_test"
	@echo "... leveldb_test"
	@echo "... ycsbc"
	@echo "... core/core_workload.o"
	@echo "... core/core_workload.i"
	@echo "... core/core_workload.s"
	@echo "... core/histogram.o"
	@echo "... core/histogram.i"
	@echo "... core/histogram.s"
	@echo "... db/db_factory.o"
	@echo "... db/db_factory.i"
	@echo "... db/db_factory.s"
	@echo "... db/hashtable_db.o"
	@echo "... db/hashtable_db.i"
	@echo "... db/hashtable_db.s"
	@echo "... db/leveldb_db.o"
	@echo "... db/leveldb_db.i"
	@echo "... db/leveldb_db.s"
	@echo "... db/rocksdb_db.o"
	@echo "... db/rocksdb_db.i"
	@echo "... db/rocksdb_db.s"
	@echo "... tests/config_reader_test.o"
	@echo "... tests/config_reader_test.i"
	@echo "... tests/config_reader_test.s"
	@echo "... tests/histogram_test.o"
	@echo "... tests/histogram_test.i"
	@echo "... tests/histogram_test.s"
	@echo "... tests/leveldb_test.o"
	@echo "... tests/leveldb_test.i"
	@echo "... tests/leveldb_test.s"
	@echo "... ycsbc.o"
	@echo "... ycsbc.i"
	@echo "... ycsbc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

